### ISSUE TITLE
[PE-D][Tester B] ModuleList: Cosmetic flaw

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#209]
It seems that the Schedules pane move as the window size grows. However, should this be the case considering the module description pane doesn't grow in size as well?

Small window size:

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/7ee4e279-16f4-4ecf-b673-a30fb8edd495.png)

Large window size:

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/c1aa419b-f161-423d-afaf-6ed45fd8eddd.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Berted/ped#5

**Comment by drkkjh** [comment]
This is not a bug because there is only 1 module description for a module and hence the size is fixed around the same width and length and thus it does not need to resize itself when there is a resize for the app. However, there can be more than 1 schedule for a module and hence that is made resizeable.
